# Generated by Django 4.0.6 on 2022-10-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
