# Generated by Django 4.0.6 on 2022-10-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_doctors_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to='Images'),
        ),
    ]
