# Generated by Django 4.0.6 on 2022-10-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_remove_doctors_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='mobile',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
