# Generated by Django 4.0.6 on 2022-08-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0003_alter_userprofile_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='followings',
        ),
    ]
