# Generated by Django 4.0.6 on 2022-08-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0007_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('dispatched', 'dispatched'), ('cancelled', 'cancelled'), ('delivered', 'delivered')], default='order-placed', max_length=120),
        ),
    ]
