# Generated by Django 4.0.6 on 2022-10-01 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapi', '0008_alter_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='blogs',
            name='liked_by',
            field=models.ManyToManyField(max_length=50, to=settings.AUTH_USER_MODEL),
        ),
    ]
